import { access, mkdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { ManagedProject } from '../registry/index.ts';

export type WorkflowState = 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'done';

export function isActiveWorkflowState(state: WorkflowState): boolean {
  return state === 'todo' || state === 'in_progress' || state === 'in_review';
}

export type WorkflowSetupIssueCode =
  | 'repo_path_missing'
  | 'repo_path_not_directory'
  | 'repo_path_not_git_repo'
  | 'workspace_root_unavailable'
  | 'logs_root_unavailable'
  | 'workflow_render_failed';

export type WorkflowSetupIssue = {
  code: WorkflowSetupIssueCode;
  field: string;
  message: string;
  path?: string;
};

export type WorkflowRenderResult = {
  projectId: string;
  workflowPath: string;
  repoPath: string;
  workspaceRoot: string;
  logsRoot: string;
  content: string;
};

export type WorkflowSetupValidation = {
  ok: boolean;
  projectId: string;
  workflowPath: string;
  repoPath: string;
  workspaceRoot: string;
  logsRoot: string;
  issues: WorkflowSetupIssue[];
  workflow?: WorkflowRenderResult;
};

export async function renderProjectWorkflow(project: ManagedProject): Promise<WorkflowRenderResult> {
  const repoPath = resolve(project.repo.path);
  const workspaceRoot = resolve(project.symphony.workspaceRoot);
  const logsRoot = resolve(project.symphony.logsRoot);
  const workflowPath = project.workflow.source === 'repo'
    ? resolve(repoPath, project.workflow.path)
    : join(workspaceRoot, 'WORKFLOW.md');

  const content = [
    '# Symphony Project Workflow',
    '',
    'This workflow file is generated by the Symphony meta-orchestrator.',
    '',
    '```yaml',
    `project_slug: ${quoteYaml(project.id)}`,
    `project_name: ${quoteYaml(project.name)}`,
    `local_repo_path: ${quoteYaml(repoPath)}`,
    `repo_clone_source: ${quoteYaml(project.repo.cloneSource)}`,
    `default_branch: ${quoteYaml(project.repo.defaultBranch)}`,
    `workspace_root: ${quoteYaml(workspaceRoot)}`,
    `logs_root: ${quoteYaml(logsRoot)}`,
    'linear:',
    `  team_key: ${quoteYaml(project.tracker.teamKey)}`,
    `  team_id: ${quoteYaml(project.tracker.teamId)}`,
    `  project_id: ${quoteYaml(project.tracker.projectId)}`,
    `  project_slug: ${quoteYaml(project.tracker.projectSlug)}`,
    'symphony:',
    `  command: ${quoteYaml(project.symphony.command)}`,
    `  runner_port: ${project.symphony.runnerPort}`,
    project.symphony.dashboardUrl ? `  dashboard_url: ${quoteYaml(project.symphony.dashboardUrl)}` : undefined,
    'codex:',
    `  thread_sandbox: ${quoteYaml(project.codex.threadSandbox)}`,
    `  turn_sandbox: ${quoteYaml(project.codex.turnSandbox)}`,
    '```',
    '',
    '## Runner Handoff',
    '',
    `- Project slug: ${project.id}`,
    `- Local repo path: ${repoPath}`,
    `- Workspace root: ${workspaceRoot}`,
    `- Logs root: ${logsRoot}`,
    '',
    'Use this file as the runner handoff contract. Do not patch paths by hand.'
  ].filter((line): line is string => line !== undefined).join('\n');

  return { projectId: project.id, workflowPath, repoPath, workspaceRoot, logsRoot, content };
}

export async function validateProjectWorkflowSetup(project: ManagedProject): Promise<WorkflowSetupValidation> {
  const issues: WorkflowSetupIssue[] = [];
  let workflow: WorkflowRenderResult | undefined;

  try {
    workflow = await renderProjectWorkflow(project);
  } catch (error) {
    issues.push({
      code: 'workflow_render_failed',
      field: 'workflow',
      message: `Workflow could not be rendered: ${error instanceof Error ? error.message : String(error)}`
    });
  }

  const repoPath = workflow?.repoPath ?? resolve(project.repo.path);
  const workspaceRoot = workflow?.workspaceRoot ?? resolve(project.symphony.workspaceRoot);
  const logsRoot = workflow?.logsRoot ?? resolve(project.symphony.logsRoot);
  const workflowPath = workflow?.workflowPath ?? (
    project.workflow.source === 'repo' ? resolve(project.repo.path, project.workflow.path) : join(workspaceRoot, 'WORKFLOW.md')
  );

  await validateRepoPath(repoPath, issues);
  await validateWritableDirectory(workspaceRoot, 'workspaceRoot', 'workspace_root_unavailable', issues);
  await validateWritableDirectory(logsRoot, 'logsRoot', 'logs_root_unavailable', issues);

  return {
    ok: issues.length === 0,
    projectId: project.id,
    workflowPath,
    repoPath,
    workspaceRoot,
    logsRoot,
    issues,
    workflow
  };
}

export async function validateProjectWorkflowSetups(projects: ManagedProject[]): Promise<WorkflowSetupValidation[]> {
  return Promise.all(projects.map((project) => validateProjectWorkflowSetup(project)));
}

export async function writeProjectWorkflow(project: ManagedProject): Promise<WorkflowRenderResult> {
  const validation = await validateProjectWorkflowSetup(project);

  if (!validation.ok || validation.workflow === undefined) {
    throw new WorkflowSetupValidationError([validation]);
  }

  await mkdir(validation.workspaceRoot, { recursive: true });
  await mkdir(validation.logsRoot, { recursive: true });
  await mkdir(dirname(validation.workflowPath), { recursive: true });
  await writeFile(validation.workflowPath, validation.workflow.content, 'utf8');
  return validation.workflow;
}

export class WorkflowSetupValidationError extends Error {
  readonly validations: WorkflowSetupValidation[];

  constructor(validations: WorkflowSetupValidation[]) {
    const issues = validations.flatMap((validation) => validation.issues);
    super(`Invalid workflow setup:\n${issues.map((issue) => `- ${issue.field}: ${issue.message}`).join('\n')}`);
    this.name = 'WorkflowSetupValidationError';
    this.validations = validations;
  }
}

async function validateRepoPath(repoPath: string, issues: WorkflowSetupIssue[]): Promise<void> {
  try {
    const repoStat = await stat(repoPath);

    if (!repoStat.isDirectory()) {
      issues.push({
        code: 'repo_path_not_directory',
        field: 'repo.path',
        message: 'Repo path exists but is not a directory',
        path: repoPath
      });
      return;
    }
  } catch {
    issues.push({
      code: 'repo_path_missing',
      field: 'repo.path',
      message: 'Repo path does not exist',
      path: repoPath
    });
    return;
  }

  try {
    await access(join(repoPath, '.git'));
  } catch {
    issues.push({
      code: 'repo_path_not_git_repo',
      field: 'repo.path',
      message: 'Repo path is not a git repository',
      path: repoPath
    });
  }
}

async function validateWritableDirectory(
  path: string,
  field: string,
  code: Extract<WorkflowSetupIssueCode, 'workspace_root_unavailable' | 'logs_root_unavailable'>,
  issues: WorkflowSetupIssue[]
): Promise<void> {
  try {
    await mkdir(path, { recursive: true });
  } catch (error) {
    issues.push({
      code,
      field,
      message: `Directory could not be created: ${error instanceof Error ? error.message : String(error)}`,
      path
    });
  }
}

function quoteYaml(value: string): string {
  return JSON.stringify(value);
}
